alias vim="nvim"
alias vi="nvim"
alias ls="ls -lAhG"
alias resource="source ~/.zshrc"
alias mux="tmuxinator"
alias psgrep="ps aux | grep -v grep | grep"
alias enpass="enpass -vault=/Users/pmggio/Library/Containers/in.sinew.Enpass-Desktop/Data/Documents/Vaults/primary/ -sort"
